services:
  - type: web
    name: ssag-command-center-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    autoDeploy: true
